export const LIST_NOEUDS_LOADING = 'LIST_NOEUDS_LOADING';
export const LIST_NOEUDS_SUCCESS = 'LIST_NOEUDS_SUCCESS';
export const LIST_NOEUDS_FAILURE = 'LIST_NOEUDS_FAILURE';
export const DETAILS_NOEUD_LOADING = 'DETAILS_NOEUD_LOADING';
export const DETAILS_NOEUD_SUCCESS = 'DETAILS_NOEUD_SUCCESS';
export const DETAILS_NOEUD_FAILURE = 'DETAILS_NOEUD_FAILURE';